package com.kumpali.security_info

object Constdata {

    val rootsAppPackage = arrayOf(
        "com.noshufou.android.su",
        "com.noshufou.android.su.elite",
        "eu.chainfire.supersu",
        "com.koushikdutta.superuser",
        "com.thirdparty.superuser",
        "com.yellowes.su",
        "com.topjohnwu.magisk",
        "com.kingroot.kinguser",
        "com.kingo.root",
        "com.smedialink.oneclickroot",
        "com.zhiqupk.root.global",
        "com.alephzain.framaroot",
        "com.keramidas.TitaniumBackup",
        "com.estrongs.android.pop",
        "com.speedsoftware.rootexplorer",
        "com.adaway.adaway",
        "com.netguard.netguard",
        "com.cleanmaster.android.cand",
        "com.symantec.mobile.security",
        "com.termux",
        "com.cooliris.tasker",
        "com.rhmsoft.flashify",
        "com.viper.viper4android",
        "com.jamesdps.android",
        "pl.solidexplorer2",
        "com.orange.oab"
    )

    val dangerousListApps = arrayOf(
        "com.koushikdutta.rommanager",
        "com.koushikdutta.rommanager.license",
        "com.dimonvideo.luckypatcher",
        "com.chelpus.lackypatch",
        "com.ramdroid.appquarantine",
        "com.ramdroid.appquarantinepro",
        "com.android.vending.billing.InAppBillingService.COIN",
        "com.android.vending.billing.InAppBillingService.LUCK",
        "com.chelpus.luckypatcher",
        "com.blackmartalpha",
        "org.blackmart.market",
        "com.allinone.free",
        "com.repodroid.app",
        "org.creeplays.hack",
        "com.baseappfull.fwd",
        "com.zmapp",
        "com.dv.marketmod.installer",
        "org.mobilism.android",
        "com.android.wp.net.log",
        "com.android.camera.update",
        "cc.madkite.freedom",
        "com.solohsu.android.edxp.manager",
        "org.meowcat.edxposed.manager",
        "com.xmodgame",
        "com.cih.game_cih",
        "com.charles.lpoqasert",
        "catch_.me_.if_.you_.can_",
        "com.anomenforyou.essentialhoroscope",
        "com.littleray.skineditorforpeminecraft",
        "com.vyblystudio.dotslinkpuzzles",
        "com.autoclickrepeater.free",
        "com.lakhinstudio.counteasycaloriecalculator",
        "com.muranogames.easyworkoutsathome",
        "com.regaliusgames.llinkgame",
        "com.Ushak.NPHOROSCOPENUMBER",
        "com.browgames.stepkeepereasymeter",
        "com.shvetsStudio.trackYourSleep",
        "com.devapps.soundvolumebooster",
        "com.Osinko.HoroscopeTaro",
        "com.Potap64.universalcalculator",
        "de.canyumusak.androiddrop",
        "com.kuaiyin.tick",
        "com.devoloperjose007.fondodeperro",
        "com.klgmedia.puzzlebox",
        "com.fillword.cross.wordmind.en",
        "com.funnypixels.games.dig_it",
        "com.errorsevendev.games.laserBreakPaid",
        "com.bitmango.wordscrush",
        "com.audio.roam",
        "com.jrdcom.filemanager",
    )

    val rootCloakingApps = arrayOf(
        "com.devadvance.rootcloak",
        "com.devadvance.rootcloakplus",
        "de.robv.android.xposed.installer",
        "com.saurik.substrate",
        "com.zachspong.temprootremovejb",
        "com.amphoras.hidemyroot",
        "com.amphoras.hidemyrootadfree",
        "com.formyhm.hiderootPremium",
        "com.formyhm.hideroot"
    )

    val superUserPath = arrayOf(
        "/data/local/su",
        "/data/local/bin/su",
        "/data/local/xbin/su",
        "/sbin/su",
        "/su/bin/su",
        "/system/bin/su",
        "/system/bin/.ext/su",
        "/system/bin/failsafe/su",
        "/system/sd/xbin/su",
        "/system/usr/we-need-root/su",
        "/system/xbin/su",
        "/cache/su",
        "/data/su",
        "/dev/su",
        "/data/adb/magisk",
        "/data/adb/.magisk",
        "/data/adb/magisk/busybox",
        "/data/adb/.magisk/busybox",
        "/system/xbin/daemonsu",
        "/data/adb/magisk.img",
        "/data/adb/magisk",
        "/data/adb/.magisk",
    )

    val notWritablePath = arrayOf(
        "/system",
        "/system/bin",
        "/system/sbin",
        "/system/xbin",
        "/vendor/bin",
        "/sbin",
        "/etc",
    )

}

